# Generated by Django 3.1.2 on 2020-11-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerOrder', '0002_auto_20201120_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='deliverd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='handeld',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
